clear all;
addpath('../../../source/matlab/lib')

task = 'eigen_dense';

path = sprintf('/data/condmat/ivanchen/yusipov/os_lnd/serial/super_decoh/%s', task);

method = 'simple';
G_type = 0;
ad = 0;
reshuffle_type = 0;

Ns = [64]';
ps = [1]';

num_seeds_total = 100000;
num_seeds_serial = 100;
num_runs = round(num_seeds_total / num_seeds_serial);
num_seeds = 1000000;

seeds = linspace(0, num_seeds_total - num_seeds_serial, num_runs)' + 1;

for N_id = 1:size(Ns, 1)
    
    N = Ns(N_id);
    N2 = N * N;
    
    for p_id = 1:size(ps, 1)
        
        p = ps(p_id);
        fprintf('p = %0.16e\n', p);
        
        rho_evals_all = zeros(N * num_seeds_total, 1);
        
        for seed_id = 1:size(seeds, 1)
            
            seed_s = seeds(seed_id)
            seed_f = seed_s + num_seeds_serial - 1;
            
            suffix = sprintf('serial(%0.4f_%0.4f_%d)_reshuffle(%d)_G(%d)_N(%d)_ad(%d)_p(%0.4f)', ...
                seed_s, ...
                1, ...
                num_seeds_serial, ...
                reshuffle_type, ...
                G_type, ...
                N, ...
                ad, ...
                p);
            
            prefix = sprintf('%s/method_%s/G_type_%d_ad_%d/reshuffle_type_%d/N_%d/p_%0.4f/seed_%d', ...
                path, ...
                method, ...
                G_type, ...
                ad, ...
                reshuffle_type, ...
                N, ...
                p, ...
                seed_s);
            
            fn = sprintf('%s/serial_rho_evals_%s.txt', ...
                prefix, ...
                suffix);
            rho_evals_data = importdata(fn);
            evals = zeros(N, 1);
            for str_id = 1:N * num_seeds_serial
                str = string(rho_evals_data(str_id));
                data2d = sscanf(str, '(%e,%e)', 2);
                evals(str_id) = data2d(1) + 1i * data2d(2);
            end
            rho_evals_all((seed_s - 1) * N + 1 : seed_f * N) = evals;
            
        end
        
        prefix = sprintf('method_%s/G_type_%d_ad_%d/reshuffle_type_%d/N_%d/p_%0.4f', ...
            method, ...
            G_type, ...
            ad, ...
            reshuffle_type, ...
            N, ...
            p);
        
        aggr_path = sprintf('%s/aggregator/%s', ...
            path, ...
            prefix);
        mkdir(aggr_path);
        
        suffix = sprintf('reshuffle(%d)_G(%d)_ad(0)_N(%d)_p(%0.10f)_seeds(%d_%d_%d)', ...
            reshuffle_type, ...
            G_type, ...
            N, ...
            p, ...
            1, ...
            1, ...
            num_seeds_total);
        
        fn_txt = sprintf('%s/rho_evals_%s.txt', aggr_path, suffix);
        fid = fopen(fn_txt,'wt');
        for x_id = 1:size(rho_evals_all, 1)
            fprintf(fid,'%0.16e %0.16e\n', real(rho_evals_all(x_id)), imag(rho_evals_all(x_id)));
        end
        fclose(fid);
        
    end
end
